#!/usr/bin/perl

use strict;
use warnings;
use File::Copy qw(copy);

my $commandString;
my $coordFile;
my $angleFile;
my $bondsFile;
my @stepDir;

$coordFile = $ARGV[0];
$angleFile = $ARGV[1];
$bondsFile = $ARGV[2];
$step = $ARGV[3];

if ($step == 0)
{
   # STEP ZERO

   # Compute the density of each time step and report it.

   open (COORD,"<$coordFile") || die "Cannot open $coordFile for reading.\n";

}
elsif ($step == 1)
{
   # STEP ONE

   $stepDir[1] = "1.remvH";
   $stepDir[2] = "2.lmpMinNoH";
   $stepDir[3] = "3.protonate";
   $stepDir[4] = "4.niceProt";
   $stepDir[5] = "5.hPercent";
   $stepDir[6] = "6.lmpMin";
   $stepDir[7] = "7.olcaoPrep";

   foreach my $dir (1..7)
      {mkdir $stepDir[$dir];}

   &copy $coordFile $stepDir[1];
   &copy $angleFile $stepDir[1];
   &copy $bondsFile $stepDir[1];
   chdir $stepDir[1];
   $commandString = "removeFreeH -dump $coordFile -bond $bondsFile ".
           "-angle $angleFile -t $timeStep";
   system("$commandString");
   chdir "..";
}

elsif ($step == 2)
{
   # STEP TWO

   mkdir "$stepDir[2]/dump2data";
   mkdir "$stepDir[2]/minimize";
   
   &copy "$stepDir[1]/coord.out" "$stepDir[2]/dump2data";
   &copy "$stepDir[1]/angle.out" "$stepDir[2]/dump2data";
   &copy "$stepDir[1]/bond.out"  "$stepDir[2]/dump2data";
   chdir "$stepDir[2]/dump2data";
   $commandString = "dump2data -dump coord.out -bond bond.out -angle ".
                    "angle.out -t $timeStep -title Empty -n data.2.lmpMinNoH";
   system("$commandString");

   chdir "../minimize";
   &copy "../dump2data/data.2.lmpMinNoH" ".";
   open (LMPIN,">in.2.lmpMinNoH") || die "Cannot open in.2.lmpMinNoH\n";
   print LMPIN <<ENDLMPIN;
units real
dimension 3
boundary p p p
atom_style full
pair_style lj/cut 15.0
bond_style harmonic
angle_style harmonic
neigh_modify every 1 delay 0 one 10000 page 150000

communicate single cutoff 20.0
pair_modify shift yes
newton off
read_data data.2.lmpMinNoH
special_bonds lj/coul 0 1 1 extra $numAtoms
timestep 0.0005
minimize 1.0e-15 1.0e-15 10000 1000000
ENDLMPIN
   close (LMPIN);
}

elsif ($step == 3)
{
   &copy "$stepDir[2]/minimize/dump.2.lmpMinNoH" "$stepDir[3]";
   &copy "$stepDir[2]/minimize/dump.2.lmpMinNoH.angle" "$stepDir[3]";
   &copy "$stepDir[2]/minimize/dump.2.lmpMinNoH.bond" "$stepDir[3]";
   $commandString = "protonate -v -title Empty -dump dump.2.lmpMinNoH -bond ".
                    "dump.2.lmpMinNoH.bond -angle dump.2.lmpMinNoH.angle -f -1";
   system("$commandString");
   
}
